import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import * as S from "./styles";

const Home: NextPage = () => {
  return (
    <S.Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">
          Welcome to <Link href="/settings">Flag Example!</Link>
        </h1>
      </main>

      <footer className="footer">
      </footer>
    </S.Container>
  );
}

export default Home;
